apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: eateazy
spec:
  selector:
    app: restaurant-service
  ports:
    - protocol: TCP
      port: 4002     # External port
      targetPort: 4002  # Port inside the container
  type: ClusterIP  # Internal communication only
