apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: panchalisam/auth-service:latest
          ports:
            - containerPort: 4001
          env:
            - name: PORT
              value: "4001"
            - name: DATABASE_URL
              value: "mysql://root:MySQL*123@host.docker.internal:3306/eatEazy_users"
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_HOST
              value: "host.docker.internal"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "MySQL*123"
            - name: DATABASE_NAME
              value: "eatEazy_users"
            - name: JWT_SECRET
              value: "2c22f96cc4f4b71adcb0e10d98749d6996ea89220724c8cad66aa8201a97da81e459198a1ea493819fe0652890b69fe3a009572f17443ae6cde7bd878285bfde9bff26783878b712341df109cd9a13d148dadfda708d65957ec6c357edb8370240146d9b832f1950c4f9deff57f64a45050f5c590fc8c9c3314df8ff32c3dc98fad92e17e12426f2d865d3bdd0dc86891860593039702706919f0cb2d2d3e5fcba699d1bc799f5d0f5f3e699b2b6bc94123f3b819ad48b146ee7a690b7b8633cb3662820bbb554aa06c8bdcd26bf7023f3f63a8a608689149c801486efcf45c7ab13c5e3f13119b1745e8a74987bb0a098e93b8634c7314f128cd5eed65cd08d"
            - name: JWT_EXPIRATION
              value: "1h"
            - name: REFRESH_TOKEN_EXPIRATION
              value: "7d"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 4001
  type: ClusterIP
