apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: eateazy
  labels:
    app: auth-service
spec:
  replicas: 2  # Adjust based on load
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest  # Replace with your actual image
          ports:
            - containerPort: 4001
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-service-secret
          resources:
            limits:
              memory: "80Mi"
              cpu: "200m"
            requests:
              memory: "80Mi"
              cpu: "100m"
