apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: eateazy
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 4001      # External port
      targetPort: 4001  # Port inside the container
  type: ClusterIP  # Internal communication only
