apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005
  type: NodePort # or LoadBalancer if using Minikube/cloud
